# This is a basic workflow to help you get started with Actions

name: Azure deployment build
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Java version 
      - name: Setup Java version
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8

      # Run maven build
      - name: Run a maven build command
        run: mvn clean install
        
        # Verify the build 
      - name: list of files in root directory 
        run: ls -a
        
        # Verify build in target directory
      - name: list of files in target directory 
        run: ls -a target/
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: nawaz462
          password: Nawaz@786
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nawaz462/azuredeployment:latest
        
        
        
